export const Users = [
    {
      id:1,
      profilePicture: "bear.jpeg",
      username: "ken",
      EECS16A: 1,
      EECS16B: 1,
      CS61A: 1,
      CS61B: 1,
      CS70: 1,
      ZOOM: 1,
      WEEKEND: 1,
      description: "I am Ken."
    },
    {
      id:2,
      profilePicture: "https://cdn.vox-cdn.com/thumbor/4rJ7OdYmzECdCYZCms00CyNZyyg=/0x0:5568x3712/1200x0/filters:focal(0x0:5568x3712):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/11816637/usa_today_10376139.jpg",
      username: "john",
      EECS16A: 1,
      EECS16B: 1,
      CS61A: 1,
      CS61B: 1,
      CS70: 1,
      ZOOM: 1,
      WEEKEND: 1,
      description: "I am a junior transfer majoring in EECS. Currently taking 16B, 61B, 198. I am open to work on campus and free on weekend. I am looking for a studybear."
    },
    {
      id:3,
      profilePicture: "bear.jpeg",
      username: "cat",
      EECS16A: 1,
      EECS16B: 0,
      CS61A: 1,
      CS61B: 0,
      CS70: 1,
      ZOOM: 1,
      WEEKEND: 0,
      description: "I am a junior transfer majoring in EECS. Currently taking 16B, 61B, 198. I am open to work on campus and free on weekend. I am looking for a studybear."
    },
    {
      id:4,
      profilePicture: "bear.jpeg",
      username: "dog",
      EECS16A: 0,
      EECS16B: 0,
      CS61A: 1,
      CS61B: 1,
      CS70: 1,
      ZOOM: 1,
      WEEKEND: 1,
      description: "I am a junior transfer majoring in EECS. Currently taking 16B, 61B, 198. I am open to work on campus and free on weekend. I am looking for a studybear."
    },
    {
      id:5,
      profilePicture: "bear.jpeg",
      username: "fish",
      EECS16A: 0,
      EECS16B: 0,
      CS61A: 1,
      CS61B: 0,
      CS70: 0,
      ZOOM: 1,
      WEEKEND: 0,
    },
    {
      id:6,
      profilePicture: "bear.jpeg",
      username: "bang",
      EECS16A: 0,
      EECS16B: 1,
      CS61A: 0,
      CS61B: 1,
      CS70: 0,
      ZOOM: 0,
      WEEKEND: 1,
    },
    {
      id:7,
      profilePicture: "bear.jpeg",
      username: "ptt",
      EECS16A: 0,
      EECS16B: 0,
      CS61A: 0,
      CS61B: 0,
      CS70: 0,
      ZOOM: 0,
      WEEKEND: 0,
    },
  ];
